const goats = [
  {
    id: 'goat1',
    name: 'Billy',
    disposition: 'rude',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg',
    fullness: 67,
    favPose: 'Downward Facing Dog',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat2',
    name: 'Ronnie',
    disposition: 'anxious',
    imgUrl: 'https://images2.minutemediacdn.com/image/upload/c_crop,h_843,w_1500,x_0,y_0/f_auto,q_auto,w_1100/v1555172619/shape/mentalfloss/iStock-177369626_0.jpg',
    fullness: 76,
    favPose: 'Seated Forward Bend',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat3',
    name: 'Bobby',
    disposition: 'happy',
    imgUrl: 'https://pbs.twimg.com/profile_images/980547001166295041/eBs20xF4.jpg',
    fullness: 83,
    favPose: 'Warrior 1',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name: 'Ricky',
    disposition: 'dope',
    imgUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThoQKeJWOO2kXsvvtZToGi8AQtas_xrIik-szf5Y38K_YQ6aeG',
    fullness: 27,
    favPose: 'Mountain Pose',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat5',
    name: 'Mike',
    disposition: 'gnarly',
    imgUrl: 'https://i.ytimg.com/vi/O3NQzrkAhD4/maxresdefault.jpg',
    fullness: 92,
    favPose: 'Plank',
    isFainting: true,
    color: 'brown',
  },
];

export default goats;
